version: "2"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: k8s-app
    image: k8s:demo
    ports:
      - "3001:3001"
    command: bash -c "uvicorn --reload app:app --host=0.0.0.0 --port=3001"
