apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: k-s-demo
build:
  artifacts:
  - image: k8s
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'k8s_demo/**'
        dest: .
manifests:
  rawYaml:
  - k8s/namespace/namespace.yaml
  - k8s/postgress/postgres-service.yaml
  - k8s/postgress/postgres-config.yaml
  - k8s/postgress/postgres-pvc.yaml
  - k8s/postgress/postgres-pv.yaml
  - k8s/postgress/postgres-deployment.yaml
  - k8s/app/service.yaml
  - k8s/app/ingress.yaml
  - k8s/app/deployment.yaml

