apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-service
spec:
  type: LoadBalancer
  selector:
    app: k8s-demo
  ports:
    - protocol: TCP
      port: 32001
      targetPort: 3001
      nodePort: 32000
