apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  # namespace: k8s-demo-namesapace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        imagePullPolicy: "IfNotPresent"
        envFrom:
        - configMapRef:
            name: postgres-config
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgres/data
        resources:
          requests:
            memory: "500Mi"
            cpu: ".5"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-pv-claim