kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  # namespace: k8s-demo-namesapace
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"