kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/amin/Documents/data/postgres-pv-volume