apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  # namespace: k8s-demo-namesapace
  labels:
    app: k8s-demo
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password